### create user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "first_name": "poke",
    "last_name": "bos",
    "email": "rizkirobawa@gmail.com",
    "password": "123456"
}

### Get all user
GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwicGFzc3dvcmQiOm51bGwsImlhdCI6MTcxNTA3MzY5NX0.pB8eVEtsjusmxS52_zpOWG3a3HusUhG1ycRCDPIf7gQ

### Get user by id
GET http://localhost:3000/api/v1/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksIm5hbWUiOiJwb2tlIiwiZW1haWwiOiJwb2tlQGdtYWlsLmNvbSIsImlhdCI6MTcxMzcxNDE4NH0.rTMBaKCkfTD0oI5gm4l03JEqxzhH7LBpa0SLmUbMRIE

### Update profile
PUT http://localhost:3000/api/v1/users/8/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksIm5hbWUiOiJwb2tlIiwiZW1haWwiOiJwb2tlQGdtYWlsLmNvbSIsImlhdCI6MTcxMzcxNDE4NH0.rTMBaKCkfTD0oI5gm4l03JEqxzhH7LBpa0SLmUbMRIE
Content-Type: application/json

{
    "address" : "Jl. Dhamra Utara IX",
    "occupation" : "Software Engineer" 
}

### Login user
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "poke@gmail.com",
    "password": "123456"
}

### verified login
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicGFzc3dvcmQiOm51bGwsImlhdCI6MTcxNTA3Mzc4M30.lIz2B91oV3FWtzFIjLyWaKz-hZa3p7xJZ74rTN6kRuQ

### Delete user
DELETE  http://localhost:3000/api/v1/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGFzc3dvcmQiOm51bGwsImlhdCI6MTcxNTA3MzczMX0.A907SQEArZkTFa163OdqdQv3zFXUaXXrHu-WLga7hds